# Dockerfile based on README.md of the LODStats repo

FROM ubuntu:18.04

#Installation instructions:

RUN apt-get update -y && \
  apt-get install -y python-pip python-dev librdf0-dev python-librdf librdf0-dev python-librdf git raptor2-utils

RUN mkdir LODStats
ADD LODStats /LODStats

RUN cd /LODStats && \
  python setup.py build && \
  python setup.py install

