version: '2'
services:
  lodstats-execute:
    build: docker-execute
    image: lodstats-execute
    stdin_open: true
    tty: true
    volumes:
      - "./src/:/src"
      - "./src/lodstats.py:/LODStats/scripts/lodstats"
      - "./input/:/input"
      - "./output/:/output"
      - "../lovver/ontologies-2018-12-05/:/lovver"
    network_mode: bridge
  lodstats-test:
    build: docker-test
    image: lodstats-test
    volumes:
      - "./src/:/src"
      - "./src/lodstats.py:/LODStats/scripts/lodstats"
      - "./test/:/test"
    network_mode: bridge
